### ISSUE TITLE
Keep track of past transcripts?

### ISSUE THREAD

**Issue by Epiju** [ProHaller/transcript.streamlit#1]
Hi @ProHaller,

Thank you for your awesome app 👍 

There is a feature I would like to request!

It would be awesome to be able to keep track of all the past transcripts generared by the app.

Let's discuss it 😄

**Comment by ProHaller** [comment]
Sorry for the delay 
Following your suggestion, I added support for user IDs, and with that transcript and notes history. 
Tell me what you think. 
I'd love to hear your feedbacks.

**Comment by ProHaller** [comment]
Done
